# This is a sample config TOML for Weaver
debug = false
extern_port = 3030
cache_url = "redis://localhost"
cache_port = "6379"
cache_password = ""
db_url = "mongodb://0.0.0.0"
db_port = "27017"
db_password = ""
body_limit = 4096

# Plug-in options
market = true