version: '3'
services:
  cache:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data/cache
    container_name: redis-cache
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db:/data/db
    container_name: mongo-db
  valence:
    build: .
    image: valence
    ports:
      - 3030:3030
    expose:
      - 3030
    restart: always
    depends_on:
      - cache
      - db
    links:
      - cache
      - db
    volumes:
      - ${PWD}/logs:/app/logs
    container_name: valence
volumes:
  cache:
    driver: local
  db:
    driver: local
