name: build-scan
on: 
  push:
    branches: 
      - main
      - develop
      - devops-update

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build: 
    uses: ablockofficial/workflows/.github/workflows/build.yml@main
    with: 
      REGISTRY:  ${{ vars.REGISTRY }}
      REPOSITORY: ${{ vars.REPOSITORY }}
  scan-image:
    uses: ablockofficial/workflows/.github/workflows/scan-image.yml@main
    secrets: inherit
    needs: build
    with:
      IMAGE: ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}:${{ github.sha }}